services:
  db:
    build:
      dockerfile: server/build/dev/db.Dockerfile
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "shared_preload_libraries=pg_cron", "-c", "cron.database_name=test"]
    volumes:
      - data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./server
      dockerfile: build/dev/api.Dockerfile
    container_name: api
    command: ["air", "-c", "air.toml"]
    volumes:
      - ./server:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/test?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  data:
