// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UploadStatus string

const (
	UploadStatusPending    UploadStatus = "pending"
	UploadStatusProcessing UploadStatus = "processing"
	UploadStatusReady      UploadStatus = "ready"
	UploadStatusFailed     UploadStatus = "failed"
	UploadStatusExpired    UploadStatus = "expired"
	UploadStatusDeleted    UploadStatus = "deleted"
)

func (e *UploadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UploadStatus(s)
	case string:
		*e = UploadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UploadStatus: %T", src)
	}
	return nil
}

type NullUploadStatus struct {
	UploadStatus UploadStatus
	Valid        bool // Valid is true if UploadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUploadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UploadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UploadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUploadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UploadStatus), nil
}

type Avatar struct {
	ID                 uuid.UUID
	OwnerUserID        uuid.UUID
	Status             UploadStatus
	FailureReason      pgtype.Text
	Bucket             string
	ObjectKeyOriginal  string
	ObjectKeyProcessed []byte
	ContentType        string
	Size               int64
	Width              pgtype.Int4
	Height             pgtype.Int4
	CreatedAt          time.Time
	UploadedAt         pgtype.Timestamptz
	ProcessedAt        pgtype.Timestamptz
	ExpiresAt          time.Time
	DeletedAt          pgtype.Timestamptz
}

type Photo struct {
	ID                 uuid.UUID
	OwnerUserID        uuid.UUID
	Status             UploadStatus
	FailureReason      pgtype.Text
	Bucket             string
	ObjectKeyOriginal  string
	ObjectKeyProcessed []byte
	ContentType        string
	Size               int64
	Width              pgtype.Int4
	Height             pgtype.Int4
	PhotoDate          pgtype.Date
	Title              pgtype.Text
	Description        pgtype.Text
	CreatedAt          time.Time
	UploadedAt         pgtype.Timestamptz
	ProcessedAt        pgtype.Timestamptz
	ExpiresAt          time.Time
	DeletedAt          pgtype.Timestamptz
}

type Session struct {
	TokenHash         []byte
	UserID            uuid.UUID
	CreatedAt         time.Time
	LastSeenAt        time.Time
	AbsoluteExpiresAt time.Time
	RevokedAt         pgtype.Timestamptz
}

type User struct {
	ID              uuid.UUID
	UsernameKey     string
	UsernameDisplay string
	PasswordHash    string
	CreatedAt       pgtype.Timestamptz
	AvatarID        pgtype.UUID
}
