// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingPhotoRecord = `-- name: CreatePendingPhotoRecord :exec
INSERT INTO photos (
  id, owner_user_id, bucket, object_key,
  local_date, upload_expires_at,
  status
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  'pending'
)
`

type CreatePendingPhotoRecordParams struct {
	ID              uuid.UUID
	OwnerUserID     uuid.UUID
	Bucket          string
	ObjectKey       string
	LocalDate       pgtype.Date
	UploadExpiresAt time.Time
}

func (q *Queries) CreatePendingPhotoRecord(ctx context.Context, arg CreatePendingPhotoRecordParams) error {
	_, err := q.db.Exec(ctx, createPendingPhotoRecord,
		arg.ID,
		arg.OwnerUserID,
		arg.Bucket,
		arg.ObjectKey,
		arg.LocalDate,
		arg.UploadExpiresAt,
	)
	return err
}

const getPhotoRecord = `-- name: GetPhotoRecord :one
SELECT id, owner_user_id, bucket,
  object_key, upload_expires_at, status
FROM photos
WHERE id = $1
  AND owner_user_id = $2
`

type GetPhotoRecordParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
}

type GetPhotoRecordRow struct {
	ID              uuid.UUID
	OwnerUserID     uuid.UUID
	Bucket          string
	ObjectKey       string
	UploadExpiresAt time.Time
	Status          PhotoProcessingStatus
}

func (q *Queries) GetPhotoRecord(ctx context.Context, arg GetPhotoRecordParams) (GetPhotoRecordRow, error) {
	row := q.db.QueryRow(ctx, getPhotoRecord, arg.ID, arg.OwnerUserID)
	var i GetPhotoRecordRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Bucket,
		&i.ObjectKey,
		&i.UploadExpiresAt,
		&i.Status,
	)
	return i, err
}

const markPhotoReady = `-- name: MarkPhotoReady :one
UPDATE photos
  SET status = 'ready',
      uploaded_at = now()
WHERE id = $1
  AND owner_user_id = $2
  AND status = 'pending'
RETURNING id
`

type MarkPhotoReadyParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
}

func (q *Queries) MarkPhotoReady(ctx context.Context, arg MarkPhotoReadyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markPhotoReady, arg.ID, arg.OwnerUserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
