// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photo.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingPhotoUploadRecord = `-- name: CreatePendingPhotoUploadRecord :exec
INSERT INTO photos (
  id,
  owner_user_id,
  bucket,
  object_key_original,
  content_type,
  size,
  photo_date,
  title,
  description,
  expires_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
`

type CreatePendingPhotoUploadRecordParams struct {
	ID                uuid.UUID
	OwnerUserID       uuid.UUID
	Bucket            string
	ObjectKeyOriginal string
	ContentType       string
	Size              int64
	PhotoDate         pgtype.Date
	Title             pgtype.Text
	Description       pgtype.Text
	ExpiresAt         time.Time
}

func (q *Queries) CreatePendingPhotoUploadRecord(ctx context.Context, arg CreatePendingPhotoUploadRecordParams) error {
	_, err := q.db.Exec(ctx, createPendingPhotoUploadRecord,
		arg.ID,
		arg.OwnerUserID,
		arg.Bucket,
		arg.ObjectKeyOriginal,
		arg.ContentType,
		arg.Size,
		arg.PhotoDate,
		arg.Title,
		arg.Description,
		arg.ExpiresAt,
	)
	return err
}

const markPhotoUploadRecordProcessing = `-- name: MarkPhotoUploadRecordProcessing :one
UPDATE photos
  SET status = 'processing',
      uploaded_at = now()
WHERE id = $1
  AND owner_user_id = $2
  AND status = 'pending'
RETURNING
  id,
  owner_user_id,
  bucket,
  object_key_original,
  content_type,
  size,
  photo_date,
  status
`

type MarkPhotoUploadRecordProcessingParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
}

type MarkPhotoUploadRecordProcessingRow struct {
	ID                uuid.UUID
	OwnerUserID       uuid.UUID
	Bucket            string
	ObjectKeyOriginal string
	ContentType       string
	Size              int64
	PhotoDate         pgtype.Date
	Status            UploadStatus
}

func (q *Queries) MarkPhotoUploadRecordProcessing(ctx context.Context, arg MarkPhotoUploadRecordProcessingParams) (MarkPhotoUploadRecordProcessingRow, error) {
	row := q.db.QueryRow(ctx, markPhotoUploadRecordProcessing, arg.ID, arg.OwnerUserID)
	var i MarkPhotoUploadRecordProcessingRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Bucket,
		&i.ObjectKeyOriginal,
		&i.ContentType,
		&i.Size,
		&i.PhotoDate,
		&i.Status,
	)
	return i, err
}

const markProcessedPhotoUploadRecordCompleted = `-- name: MarkProcessedPhotoUploadRecordCompleted :one
UPDATE photos
  SET status = 'ready',
      processed_at = now(),
      object_key_processed = $1,
      width = $2,
      height = $3
WHERE id = $4
  AND owner_user_id = $5
  AND status = 'processing'
RETURNING id
`

type MarkProcessedPhotoUploadRecordCompletedParams struct {
	ObjectKeyProcessed []byte
	Width              pgtype.Int4
	Height             pgtype.Int4
	ID                 uuid.UUID
	OwnerUserID        uuid.UUID
}

func (q *Queries) MarkProcessedPhotoUploadRecordCompleted(ctx context.Context, arg MarkProcessedPhotoUploadRecordCompletedParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markProcessedPhotoUploadRecordCompleted,
		arg.ObjectKeyProcessed,
		arg.Width,
		arg.Height,
		arg.ID,
		arg.OwnerUserID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markProcessedPhotoUploadRecordFailed = `-- name: MarkProcessedPhotoUploadRecordFailed :one
UPDATE photos
  SET status = 'failed',
      failure_reason = $1
WHERE id = $2
  AND owner_user_id = $3
  AND status = 'processing'
RETURNING id
`

type MarkProcessedPhotoUploadRecordFailedParams struct {
	FailureReason pgtype.Text
	ID            uuid.UUID
	OwnerUserID   uuid.UUID
}

func (q *Queries) MarkProcessedPhotoUploadRecordFailed(ctx context.Context, arg MarkProcessedPhotoUploadRecordFailedParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markProcessedPhotoUploadRecordFailed, arg.FailureReason, arg.ID, arg.OwnerUserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
