// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingPhotoRecord = `-- name: CreatePendingPhotoRecord :exec
INSERT INTO photos (
  id, owner_user_id, bucket, object_key,
  local_date, upload_expires_at,
  status
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  'pending'
)
`

type CreatePendingPhotoRecordParams struct {
	ID              uuid.UUID
	OwnerUserID     uuid.UUID
	Bucket          string
	ObjectKey       string
	LocalDate       pgtype.Date
	UploadExpiresAt time.Time
}

func (q *Queries) CreatePendingPhotoRecord(ctx context.Context, arg CreatePendingPhotoRecordParams) error {
	_, err := q.db.Exec(ctx, createPendingPhotoRecord,
		arg.ID,
		arg.OwnerUserID,
		arg.Bucket,
		arg.ObjectKey,
		arg.LocalDate,
		arg.UploadExpiresAt,
	)
	return err
}

const updatePhotoRecordStatus = `-- name: UpdatePhotoRecordStatus :exec
UPDATE photos
  SET status = $1
WHERE id = $2
  AND owner_user_id = $3
  AND status = 'pending'
`

type UpdatePhotoRecordStatusParams struct {
	Status      PhotoProcessingStatus
	ID          uuid.UUID
	OwnerUserID uuid.UUID
}

func (q *Queries) UpdatePhotoRecordStatus(ctx context.Context, arg UpdatePhotoRecordStatusParams) error {
	_, err := q.db.Exec(ctx, updatePhotoRecordStatus, arg.Status, arg.ID, arg.OwnerUserID)
	return err
}
