// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (
  id, user_id, token, expires_at
) VALUES (
  $1, $2, $3, $4
)
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username_key, username_display, password_hash
) VALUES (
  $1, $2, $3
)
RETURNING username_key, username_display
`

type CreateUserParams struct {
	UsernameKey     string
	UsernameDisplay string
	PasswordHash    string
}

type CreateUserRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UsernameKey, arg.UsernameDisplay, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}

const deleteAllRefreshTokensByUserID = `-- name: DeleteAllRefreshTokensByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteAllRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllRefreshTokensByUserID, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE username_key = $1
`

func (q *Queries) DeleteUser(ctx context.Context, usernameKey string) error {
	_, err := q.db.Exec(ctx, deleteUser, usernameKey)
	return err
}

const getFullUserDataByKey = `-- name: GetFullUserDataByKey :one
SELECT id, username_key, username_display, password_hash FROM users
WHERE username_key = $1
`

type GetFullUserDataByKeyRow struct {
	ID              uuid.UUID
	UsernameKey     string
	UsernameDisplay string
	PasswordHash    string
}

func (q *Queries) GetFullUserDataByKey(ctx context.Context, usernameKey string) (GetFullUserDataByKeyRow, error) {
	row := q.db.QueryRow(ctx, getFullUserDataByKey, usernameKey)
	var i GetFullUserDataByKeyRow
	err := row.Scan(
		&i.ID,
		&i.UsernameKey,
		&i.UsernameDisplay,
		&i.PasswordHash,
	)
	return i, err
}

const getPublicUserProfile = `-- name: GetPublicUserProfile :one
SELECT username_key, username_display FROM users
WHERE username_key = $1
`

type GetPublicUserProfileRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) GetPublicUserProfile(ctx context.Context, usernameKey string) (GetPublicUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getPublicUserProfile, usernameKey)
	var i GetPublicUserProfileRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}

const revokeActiveToken = `-- name: RevokeActiveToken :one
UPDATE refresh_tokens
SET revoked = true
WHERE id = $1
  AND revoked = false
  AND expires_at > now()
RETURNING user_id
`

func (q *Queries) RevokeActiveToken(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeActiveToken, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
  set username_key = $2,
  username_display = $3
WHERE username_key = $1
RETURNING username_key, username_display
`

type UpdateUserParams struct {
	UsernameKey     string
	UsernameKey_2   string
	UsernameDisplay string
}

type UpdateUserRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.UsernameKey, arg.UsernameKey_2, arg.UsernameDisplay)
	var i UpdateUserRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}
