// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  token_hash, user_id, created_at, last_seen_at, absolute_expires_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING token_hash
`

type CreateSessionParams struct {
	TokenHash         []byte
	UserID            uuid.UUID
	CreatedAt         time.Time
	LastSeenAt        time.Time
	AbsoluteExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.AbsoluteExpiresAt,
	)
	var token_hash []byte
	err := row.Scan(&token_hash)
	return token_hash, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username_key, username_display, password_hash
) VALUES (
  $1,
  $2,
  $3
)
RETURNING username_key, username_display
`

type CreateUserParams struct {
	UsernameKey     string
	UsernameDisplay string
	PasswordHash    string
}

type CreateUserRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UsernameKey, arg.UsernameDisplay, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE username_key = $1
`

func (q *Queries) DeleteUser(ctx context.Context, usernameKey string) error {
	_, err := q.db.Exec(ctx, deleteUser, usernameKey)
	return err
}

const getFullUserDataByKey = `-- name: GetFullUserDataByKey :one
SELECT id, username_key, username_display, password_hash FROM users
WHERE username_key = $1
`

type GetFullUserDataByKeyRow struct {
	ID              uuid.UUID
	UsernameKey     string
	UsernameDisplay string
	PasswordHash    string
}

func (q *Queries) GetFullUserDataByKey(ctx context.Context, usernameKey string) (GetFullUserDataByKeyRow, error) {
	row := q.db.QueryRow(ctx, getFullUserDataByKey, usernameKey)
	var i GetFullUserDataByKeyRow
	err := row.Scan(
		&i.ID,
		&i.UsernameKey,
		&i.UsernameDisplay,
		&i.PasswordHash,
	)
	return i, err
}

const getPublicUserProfile = `-- name: GetPublicUserProfile :one
SELECT username_key, username_display FROM users
WHERE username_key = $1
`

type GetPublicUserProfileRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) GetPublicUserProfile(ctx context.Context, usernameKey string) (GetPublicUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getPublicUserProfile, usernameKey)
	var i GetPublicUserProfileRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT
  token_hash,
  user_id,
  created_at,
  last_seen_at,
  absolute_expires_at,
  revoked_at
FROM sessions
WHERE token_hash = $1
`

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllSessions = `-- name: RevokeAllSessions :exec
UPDATE sessions
  SET revoked_at = $1
WHERE user_id = $2
  AND revoked_at IS NULL
`

type RevokeAllSessionsParams struct {
	RevokedAt pgtype.Timestamptz
	UserID    uuid.UUID
}

func (q *Queries) RevokeAllSessions(ctx context.Context, arg RevokeAllSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllSessions, arg.RevokedAt, arg.UserID)
	return err
}

const revokeSession = `-- name: RevokeSession :one
UPDATE sessions
  SET revoked_at = $1
WHERE token_hash = $2
  AND revoked_at IS NULL
RETURNING token_hash, revoked_at
`

type RevokeSessionParams struct {
	RevokedAt pgtype.Timestamptz
	TokenHash []byte
}

type RevokeSessionRow struct {
	TokenHash []byte
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (RevokeSessionRow, error) {
	row := q.db.QueryRow(ctx, revokeSession, arg.RevokedAt, arg.TokenHash)
	var i RevokeSessionRow
	err := row.Scan(&i.TokenHash, &i.RevokedAt)
	return i, err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :one
UPDATE sessions
  SET last_seen_at = $1
WHERE token_hash = $2
  AND revoked_at IS NULL
  AND absolute_expires_at > $1
RETURNING token_hash, last_seen_at
`

type UpdateSessionActivityParams struct {
	LastSeenAt time.Time
	TokenHash  []byte
}

type UpdateSessionActivityRow struct {
	TokenHash  []byte
	LastSeenAt time.Time
}

func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) (UpdateSessionActivityRow, error) {
	row := q.db.QueryRow(ctx, updateSessionActivity, arg.LastSeenAt, arg.TokenHash)
	var i UpdateSessionActivityRow
	err := row.Scan(&i.TokenHash, &i.LastSeenAt)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
  SET username_key = $1,
  username_display = $2
WHERE username_key = $3
RETURNING username_key, username_display
`

type UpdateUserParams struct {
	UsernameKey        string
	UsernameDisplay    string
	CurrentUsernameKey string
}

type UpdateUserRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.UsernameKey, arg.UsernameDisplay, arg.CurrentUsernameKey)
	var i UpdateUserRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}
