// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNewRefreshToken = `-- name: CreateNewRefreshToken :exec
INSERT INTO refresh_tokens (
  id, user_id, expires_at
) VALUES (
  $1, $2, $3
)
`

type CreateNewRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateNewRefreshToken(ctx context.Context, arg CreateNewRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createNewRefreshToken, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username_key, username_display, password_hash
) VALUES (
  $1, $2, $3
)
RETURNING username_key, username_display
`

type CreateUserParams struct {
	UsernameKey     string
	UsernameDisplay string
	PasswordHash    string
}

type CreateUserRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UsernameKey, arg.UsernameDisplay, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE username_key = $1
`

func (q *Queries) DeleteUser(ctx context.Context, usernameKey string) error {
	_, err := q.db.Exec(ctx, deleteUser, usernameKey)
	return err
}

const getFullUserDataByKey = `-- name: GetFullUserDataByKey :one
SELECT id, username_key, username_display, password_hash FROM users
WHERE username_key = $1
`

type GetFullUserDataByKeyRow struct {
	ID              uuid.UUID
	UsernameKey     string
	UsernameDisplay string
	PasswordHash    string
}

func (q *Queries) GetFullUserDataByKey(ctx context.Context, usernameKey string) (GetFullUserDataByKeyRow, error) {
	row := q.db.QueryRow(ctx, getFullUserDataByKey, usernameKey)
	var i GetFullUserDataByKeyRow
	err := row.Scan(
		&i.ID,
		&i.UsernameKey,
		&i.UsernameDisplay,
		&i.PasswordHash,
	)
	return i, err
}

const getPublicUserProfile = `-- name: GetPublicUserProfile :one
SELECT username_key, username_display FROM users
WHERE username_key = $1
`

type GetPublicUserProfileRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) GetPublicUserProfile(ctx context.Context, usernameKey string) (GetPublicUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getPublicUserProfile, usernameKey)
	var i GetPublicUserProfileRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT id, user_id, revoked, expires_at,
  grace_period_until, replaced_by_access, replaced_by_refresh
FROM refresh_tokens
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type GetRefreshTokenForUpdateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetRefreshTokenForUpdateRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Revoked           bool
	ExpiresAt         time.Time
	GracePeriodUntil  pgtype.Timestamptz
	ReplacedByAccess  pgtype.Text
	ReplacedByRefresh pgtype.Text
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, arg GetRefreshTokenForUpdateParams) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, arg.ID, arg.UserID)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Revoked,
		&i.ExpiresAt,
		&i.GracePeriodUntil,
		&i.ReplacedByAccess,
		&i.ReplacedByRefresh,
	)
	return i, err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE refresh_tokens
    SET revoked = true
WHERE user_id = $1 AND revoked = false
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens
    SET revoked = true
WHERE id = $1 AND user_id = $2 AND revoked = false
RETURNING id
`

type RevokeRefreshTokenParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeRefreshToken, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :exec
UPDATE refresh_tokens
    SET revoked = true,
    grace_period_until = $2,
    replaced_by_access = $3,
    replaced_by_refresh = $4
WHERE id = $1
`

type RotateRefreshTokenParams struct {
	ID                uuid.UUID
	GracePeriodUntil  pgtype.Timestamptz
	ReplacedByAccess  pgtype.Text
	ReplacedByRefresh pgtype.Text
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, rotateRefreshToken,
		arg.ID,
		arg.GracePeriodUntil,
		arg.ReplacedByAccess,
		arg.ReplacedByRefresh,
	)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
  SET username_key = $2,
  username_display = $3
WHERE username_key = $1
RETURNING username_key, username_display
`

type UpdateUserParams struct {
	UsernameKey     string
	UsernameKey_2   string
	UsernameDisplay string
}

type UpdateUserRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.UsernameKey, arg.UsernameKey_2, arg.UsernameDisplay)
	var i UpdateUserRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}
