// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  token_hash, user_id, created_at, last_seen_at, absolute_expires_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING token_hash
`

type CreateSessionParams struct {
	TokenHash         []byte
	UserID            uuid.UUID
	CreatedAt         time.Time
	LastSeenAt        time.Time
	AbsoluteExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.AbsoluteExpiresAt,
	)
	var token_hash []byte
	err := row.Scan(&token_hash)
	return token_hash, err
}

const getSession = `-- name: GetSession :one
SELECT
  s.token_hash,
  s.user_id,
  u.username_key,
  s.created_at,
  s.last_seen_at,
  s.absolute_expires_at,
  s.revoked_at
FROM sessions s
LEFT JOIN users u ON s.user_id = u.id
WHERE token_hash = $1
`

type GetSessionRow struct {
	TokenHash         []byte
	UserID            uuid.UUID
	UsernameKey       pgtype.Text
	CreatedAt         time.Time
	LastSeenAt        time.Time
	AbsoluteExpiresAt time.Time
	RevokedAt         pgtype.Timestamptz
}

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.UsernameKey,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionOwner = `-- name: GetSessionOwner :one
SELECT username_key, username_display FROM users
WHERE id = $1
`

type GetSessionOwnerRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) GetSessionOwner(ctx context.Context, id uuid.UUID) (GetSessionOwnerRow, error) {
	row := q.db.QueryRow(ctx, getSessionOwner, id)
	var i GetSessionOwnerRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}

const revokeAllSessions = `-- name: RevokeAllSessions :exec
UPDATE sessions
  SET revoked_at = $1
WHERE user_id = $2
  AND revoked_at IS NULL
`

type RevokeAllSessionsParams struct {
	RevokedAt pgtype.Timestamptz
	UserID    uuid.UUID
}

func (q *Queries) RevokeAllSessions(ctx context.Context, arg RevokeAllSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllSessions, arg.RevokedAt, arg.UserID)
	return err
}

const revokeSession = `-- name: RevokeSession :one
UPDATE sessions
  SET revoked_at = $1
WHERE token_hash = $2
  AND revoked_at IS NULL
RETURNING token_hash, revoked_at
`

type RevokeSessionParams struct {
	RevokedAt pgtype.Timestamptz
	TokenHash []byte
}

type RevokeSessionRow struct {
	TokenHash []byte
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (RevokeSessionRow, error) {
	row := q.db.QueryRow(ctx, revokeSession, arg.RevokedAt, arg.TokenHash)
	var i RevokeSessionRow
	err := row.Scan(&i.TokenHash, &i.RevokedAt)
	return i, err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :one
UPDATE sessions
  SET last_seen_at = $1
WHERE token_hash = $2
  AND revoked_at IS NULL
  AND absolute_expires_at > $1
RETURNING token_hash, last_seen_at
`

type UpdateSessionActivityParams struct {
	LastSeenAt time.Time
	TokenHash  []byte
}

type UpdateSessionActivityRow struct {
	TokenHash  []byte
	LastSeenAt time.Time
}

func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) (UpdateSessionActivityRow, error) {
	row := q.db.QueryRow(ctx, updateSessionActivity, arg.LastSeenAt, arg.TokenHash)
	var i UpdateSessionActivityRow
	err := row.Scan(&i.TokenHash, &i.LastSeenAt)
	return i, err
}
