// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploaded_files.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completePendingUploadRecord = `-- name: CompletePendingUploadRecord :one
UPDATE uploaded_files
  SET status = 'ready',
      uploaded_at = now(),
      processed_at = now(),
      object_key_processed = $1,
      content_type = $2,
      size = $3,
      width = $4,
      height = $5
WHERE id = $6
  AND owner_user_id = $7
  AND status = 'pending'
RETURNING id
`

type CompletePendingUploadRecordParams struct {
	ObjectKeyProcessed []byte
	ContentType        string
	Size               int64
	Width              pgtype.Int4
	Height             pgtype.Int4
	ID                 uuid.UUID
	OwnerUserID        uuid.UUID
}

func (q *Queries) CompletePendingUploadRecord(ctx context.Context, arg CompletePendingUploadRecordParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, completePendingUploadRecord,
		arg.ObjectKeyProcessed,
		arg.ContentType,
		arg.Size,
		arg.Width,
		arg.Height,
		arg.ID,
		arg.OwnerUserID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createPendingUploadRecord = `-- name: CreatePendingUploadRecord :exec
INSERT INTO uploaded_files (
  id,
  owner_user_id,
  kind,
  bucket,
  object_key_original,
  content_type,
  size,
  photo_date,
  title,
  description,
  expires_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
)
`

type CreatePendingUploadRecordParams struct {
	ID                uuid.UUID
	OwnerUserID       uuid.UUID
	Kind              UploadKind
	Bucket            string
	ObjectKeyOriginal string
	ContentType       string
	Size              int64
	PhotoDate         pgtype.Date
	Title             pgtype.Text
	Description       pgtype.Text
	ExpiresAt         time.Time
}

func (q *Queries) CreatePendingUploadRecord(ctx context.Context, arg CreatePendingUploadRecordParams) error {
	_, err := q.db.Exec(ctx, createPendingUploadRecord,
		arg.ID,
		arg.OwnerUserID,
		arg.Kind,
		arg.Bucket,
		arg.ObjectKeyOriginal,
		arg.ContentType,
		arg.Size,
		arg.PhotoDate,
		arg.Title,
		arg.Description,
		arg.ExpiresAt,
	)
	return err
}

const expirePendingUploadRecords = `-- name: ExpirePendingUploadRecords :many
UPDATE uploaded_files
  SET status = 'expired',
      failure_reason = 'unfinished_upload'
WHERE expires_at < now()
  AND status = 'pending'
RETURNING id, bucket, object_key_original
`

type ExpirePendingUploadRecordsRow struct {
	ID                uuid.UUID
	Bucket            string
	ObjectKeyOriginal string
}

func (q *Queries) ExpirePendingUploadRecords(ctx context.Context) ([]ExpirePendingUploadRecordsRow, error) {
	rows, err := q.db.Query(ctx, expirePendingUploadRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpirePendingUploadRecordsRow
	for rows.Next() {
		var i ExpirePendingUploadRecordsRow
		if err := rows.Scan(&i.ID, &i.Bucket, &i.ObjectKeyOriginal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failPendingUploadRecord = `-- name: FailPendingUploadRecord :one
UPDATE uploaded_files
  SET status = 'failed',
      failure_reason = $1
WHERE id = $2
  AND owner_user_id = $3
  AND status = 'pending'
RETURNING id
`

type FailPendingUploadRecordParams struct {
	FailureReason pgtype.Text
	ID            uuid.UUID
	OwnerUserID   uuid.UUID
}

func (q *Queries) FailPendingUploadRecord(ctx context.Context, arg FailPendingUploadRecordParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, failPendingUploadRecord, arg.FailureReason, arg.ID, arg.OwnerUserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markUploadRecordDeleted = `-- name: MarkUploadRecordDeleted :one
UPDATE uploaded_files
  SET status = 'deleted',
      deleted_at = now()
WHERE id = $1
  AND owner_user_id = $2
  AND status != 'deleted'
RETURNING id
`

type MarkUploadRecordDeletedParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
}

func (q *Queries) MarkUploadRecordDeleted(ctx context.Context, arg MarkUploadRecordDeletedParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markUploadRecordDeleted, arg.ID, arg.OwnerUserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
