// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username_key, username_display, password_hash
) VALUES (
  $1,
  $2,
  $3
)
RETURNING username_key, username_display
`

type CreateUserParams struct {
	UsernameKey     string
	UsernameDisplay string
	PasswordHash    string
}

type CreateUserRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UsernameKey, arg.UsernameDisplay, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}

const getPasswordHash = `-- name: GetPasswordHash :one
SELECT id, username_key, password_hash FROM users
WHERE id = $1
`

type GetPasswordHashRow struct {
	ID           uuid.UUID
	UsernameKey  string
	PasswordHash string
}

func (q *Queries) GetPasswordHash(ctx context.Context, userID uuid.UUID) (GetPasswordHashRow, error) {
	row := q.db.QueryRow(ctx, getPasswordHash, userID)
	var i GetPasswordHashRow
	err := row.Scan(&i.ID, &i.UsernameKey, &i.PasswordHash)
	return i, err
}

const getUserAccessProfile = `-- name: GetUserAccessProfile :one
SELECT id, profile_visibility
FROM users
WHERE username_key = $1
`

type GetUserAccessProfileRow struct {
	ID                uuid.UUID
	ProfileVisibility string
}

func (q *Queries) GetUserAccessProfile(ctx context.Context, usernameKey string) (GetUserAccessProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserAccessProfile, usernameKey)
	var i GetUserAccessProfileRow
	err := row.Scan(&i.ID, &i.ProfileVisibility)
	return i, err
}

const getUserDataForLogin = `-- name: GetUserDataForLogin :one
SELECT id, username_key, username_display, password_hash FROM users
WHERE username_key = $1
`

type GetUserDataForLoginRow struct {
	ID              uuid.UUID
	UsernameKey     string
	UsernameDisplay string
	PasswordHash    string
}

func (q *Queries) GetUserDataForLogin(ctx context.Context, usernameKey string) (GetUserDataForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserDataForLogin, usernameKey)
	var i GetUserDataForLoginRow
	err := row.Scan(
		&i.ID,
		&i.UsernameKey,
		&i.UsernameDisplay,
		&i.PasswordHash,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT
  u.id,
  u.username_key,
  u.username_display,
  u.about,
  u.profile_visibility,
  u.created_at AS joined_at,
  a.bucket AS avatar_bucket,
  a.object_key AS avatar_object_key,
  (
    SELECT COUNT(p.id)
    FROM photos p
    WHERE p.owner_user_id = u.id
      AND p.status = 'ready'
      AND p.deleted_at IS NULL
  ) AS photo_count
FROM users u
LEFT JOIN user_avatars a ON u.id = a.user_id
WHERE u.username_key = $1
`

type GetUserProfileRow struct {
	ID                uuid.UUID
	UsernameKey       string
	UsernameDisplay   string
	About             pgtype.Text
	ProfileVisibility string
	JoinedAt          pgtype.Timestamptz
	AvatarBucket      pgtype.Text
	AvatarObjectKey   pgtype.Text
	PhotoCount        int64
}

func (q *Queries) GetUserProfile(ctx context.Context, usernameKey string) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, usernameKey)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.UsernameKey,
		&i.UsernameDisplay,
		&i.About,
		&i.ProfileVisibility,
		&i.JoinedAt,
		&i.AvatarBucket,
		&i.AvatarObjectKey,
		&i.PhotoCount,
	)
	return i, err
}

const listUserPhotosAfterCursor = `-- name: ListUserPhotosAfterCursor :many
SELECT photos.id, photos.owner_user_id, photos.status, photos.failure_reason, photos.bucket, photos.object_key_original, photos.object_key_processed, photos.content_type, photos.size, photos.width, photos.height, photos.photo_date, photos.title, photos.description, photos.created_at, photos.uploaded_at, photos.processed_at, photos.expires_at, photos.deleted_at
FROM photos
WHERE owner_user_id = $1
  AND status = 'ready'
  AND deleted_at IS NULL
  AND (photo_date, id) < ($2::date, $3::uuid)
ORDER BY photo_date DESC, id DESC
LIMIT $4
`

type ListUserPhotosAfterCursorParams struct {
	UserID          uuid.UUID
	CursorPhotoDate pgtype.Date
	CursorID        uuid.UUID
	LimitCount      int32
}

func (q *Queries) ListUserPhotosAfterCursor(ctx context.Context, arg ListUserPhotosAfterCursorParams) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listUserPhotosAfterCursor,
		arg.UserID,
		arg.CursorPhotoDate,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Status,
			&i.FailureReason,
			&i.Bucket,
			&i.ObjectKeyOriginal,
			&i.ObjectKeyProcessed,
			&i.ContentType,
			&i.Size,
			&i.Width,
			&i.Height,
			&i.PhotoDate,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UploadedAt,
			&i.ProcessedAt,
			&i.ExpiresAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPhotosFirstPage = `-- name: ListUserPhotosFirstPage :many
SELECT photos.id, photos.owner_user_id, photos.status, photos.failure_reason, photos.bucket, photos.object_key_original, photos.object_key_processed, photos.content_type, photos.size, photos.width, photos.height, photos.photo_date, photos.title, photos.description, photos.created_at, photos.uploaded_at, photos.processed_at, photos.expires_at, photos.deleted_at
FROM photos
WHERE owner_user_id = $1
  AND status = 'ready'
  AND deleted_at IS NULL
ORDER BY photo_date DESC, id DESC
LIMIT $2
`

type ListUserPhotosFirstPageParams struct {
	UserID     uuid.UUID
	LimitCount int32
}

func (q *Queries) ListUserPhotosFirstPage(ctx context.Context, arg ListUserPhotosFirstPageParams) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listUserPhotosFirstPage, arg.UserID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Status,
			&i.FailureReason,
			&i.Bucket,
			&i.ObjectKeyOriginal,
			&i.ObjectKeyProcessed,
			&i.ContentType,
			&i.Size,
			&i.Width,
			&i.Height,
			&i.PhotoDate,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UploadedAt,
			&i.ProcessedAt,
			&i.ExpiresAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePasswordHash = `-- name: UpdatePasswordHash :one
UPDATE users
SET password_hash = $1,
    updated_at = now()
WHERE id = $2
  AND password_hash = $3
RETURNING id
`

type UpdatePasswordHashParams struct {
	NewPasswordHash     string
	UserID              uuid.UUID
	CurrentPasswordHash string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updatePasswordHash, arg.NewPasswordHash, arg.UserID, arg.CurrentPasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET username_display = $1,
    about = $2,
    profile_visibility = $3,
    updated_at = now()
WHERE id = $4
RETURNING
  id,
  username_key,
  username_display,
  about,
  profile_visibility
`

type UpdateUserProfileParams struct {
	DisplayName string
	About       pgtype.Text
	Visibility  string
	ID          uuid.UUID
}

type UpdateUserProfileRow struct {
	ID                uuid.UUID
	UsernameKey       string
	UsernameDisplay   string
	About             pgtype.Text
	ProfileVisibility string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.About,
		arg.Visibility,
		arg.ID,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.UsernameKey,
		&i.UsernameDisplay,
		&i.About,
		&i.ProfileVisibility,
	)
	return i, err
}

const updateUsername = `-- name: UpdateUsername :one
UPDATE users
SET username_key = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, username_key
`

type UpdateUsernameParams struct {
	NewUsernameKey string
	ID             uuid.UUID
}

type UpdateUsernameRow struct {
	ID          uuid.UUID
	UsernameKey string
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (UpdateUsernameRow, error) {
	row := q.db.QueryRow(ctx, updateUsername, arg.NewUsernameKey, arg.ID)
	var i UpdateUsernameRow
	err := row.Scan(&i.ID, &i.UsernameKey)
	return i, err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (
  SELECT 1
  FROM users
  WHERE username_key = $1
)
`

func (q *Queries) UsernameExists(ctx context.Context, usernameKey string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, usernameKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
