// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username_key, username_display, password_hash
) VALUES (
  $1,
  $2,
  $3
)
RETURNING username_key, username_display
`

type CreateUserParams struct {
	UsernameKey     string
	UsernameDisplay string
	PasswordHash    string
}

type CreateUserRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UsernameKey, arg.UsernameDisplay, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}

const getUserDataForLogin = `-- name: GetUserDataForLogin :one
SELECT id, username_key, username_display, password_hash FROM users
WHERE username_key = $1
`

type GetUserDataForLoginRow struct {
	ID              uuid.UUID
	UsernameKey     string
	UsernameDisplay string
	PasswordHash    string
}

func (q *Queries) GetUserDataForLogin(ctx context.Context, usernameKey string) (GetUserDataForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserDataForLogin, usernameKey)
	var i GetUserDataForLoginRow
	err := row.Scan(
		&i.ID,
		&i.UsernameKey,
		&i.UsernameDisplay,
		&i.PasswordHash,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT
  u.id,
  u.username_key,
  u.username_display,
  u.about,
  u.profile_visibility,
  u.created_at AS joined_at,
  a.bucket AS avatar_bucket,
  a.object_key AS avatar_object_key,
  (
    SELECT COUNT(p.id)
    FROM photos p
    WHERE p.owner_user_id = u.id
      AND p.status = 'ready'
      AND p.deleted_at IS NULL
  ) AS photo_count
FROM users u
LEFT JOIN user_avatars a ON u.id = a.user_id
WHERE u.username_key = $1
`

type GetUserProfileRow struct {
	ID                uuid.UUID
	UsernameKey       string
	UsernameDisplay   string
	About             pgtype.Text
	ProfileVisibility string
	JoinedAt          pgtype.Timestamptz
	AvatarBucket      pgtype.Text
	AvatarObjectKey   pgtype.Text
	PhotoCount        int64
}

func (q *Queries) GetUserProfile(ctx context.Context, usernameKey string) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, usernameKey)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.UsernameKey,
		&i.UsernameDisplay,
		&i.About,
		&i.ProfileVisibility,
		&i.JoinedAt,
		&i.AvatarBucket,
		&i.AvatarObjectKey,
		&i.PhotoCount,
	)
	return i, err
}
