// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username_key, username_display, password_hash
) VALUES (
  $1,
  $2,
  $3
)
RETURNING username_key, username_display
`

type CreateUserParams struct {
	UsernameKey     string
	UsernameDisplay string
	PasswordHash    string
}

type CreateUserRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UsernameKey, arg.UsernameDisplay, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}

const getUserDataForLogin = `-- name: GetUserDataForLogin :one
SELECT id, username_key, username_display, password_hash FROM users
WHERE username_key = $1
`

type GetUserDataForLoginRow struct {
	ID              uuid.UUID
	UsernameKey     string
	UsernameDisplay string
	PasswordHash    string
}

func (q *Queries) GetUserDataForLogin(ctx context.Context, usernameKey string) (GetUserDataForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserDataForLogin, usernameKey)
	var i GetUserDataForLoginRow
	err := row.Scan(
		&i.ID,
		&i.UsernameKey,
		&i.UsernameDisplay,
		&i.PasswordHash,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT username_key, username_display FROM users
WHERE username_key = $1
`

type GetUserProfileRow struct {
	UsernameKey     string
	UsernameDisplay string
}

func (q *Queries) GetUserProfile(ctx context.Context, usernameKey string) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, usernameKey)
	var i GetUserProfileRow
	err := row.Scan(&i.UsernameKey, &i.UsernameDisplay)
	return i, err
}
